### ISSUE TITLE
if shim-logs fails to forward the logs to redis, process receives SIGPIPE

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/shim-logs#1]
Related to https://github.com/threefoldtech/zos/issues/943

The redis was started with default arguments hence it doesn't allow remote client to do any write/read operations the process inside the container kept getting SIGPIPE.

restarting redis to run in (non-protected mode) the process was still not able to processed (same signal) a new container needed to be created for this to work again.

Possible solution:
If the shim can not forward the logs, it still need to read stdout/stderr ? (how to tell the user that his setup is wrong).

**Comment by maxux** [comment]
Or something else need to confirm that user input are valid and tested before starting the shim-logs (which expect a valid config).

**Comment by muhamadazmy** [comment]
Do you support passowrds in the URL ? this is needed to make sure we support protected redis instances

**Comment by muhamadazmy** [comment]
Yeah, testing the endpoint is also a good option, but it also mean if the connection was lost or something else happened, that the contained process will die.

**Comment by maxux** [comment]
It's supported by url parser (afaik) but not used, can be added easily, can you open a dedicated issue for that ?
